image: node:12.13.0

stages:
  - build
  - test

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

build:
  stage: build
  before_script:
    - npm set registry https://registry.npm.taobao.org
  script: 
    - npm install --progress=false
    
test:
  stage: test
  script:
    - npm run test:unit
    - SUFFIX=$RANDOM
    - curl "http://10.0.0.11/sonar-scanner.tar.gz" -s -o "/tmp/sonar-$SUFFIX.tar.gz"
    - tar -xf "/tmp/sonar-$SUFFIX.tar.gz"  -C /opt
    - /opt/sonar-scanner/bin/sonar-scanner

